### ISSUE TITLE
Not working with Angular2 rc5

### ISSUE THREAD

**Issue by Ks89** [vimalavinisha/angular2-image-popup#6]
I'm using angular2 rc5 + typescript2.0.0 and when I install this library I receive this error:

> angular2-image-popup@1.0.8 postinstall (...)
> typings install

/usr/local/lib/node_modules/typings/node_modules/configstore/index.js:54
                    throw err;
                    ^

Error: EACCES: permission denied, open '/(...)/.config/configstore/typings.json'
You don't have access to this file.

```
at Error (native)
at Object.fs.openSync (fs.js:640:18)
at Object.fs.readFileSync (fs.js:508:33)
at Object.create.all.get (/usr/local/lib/node_modules/typings/node_modules/configstore/index.js:35:26)
at Object.Configstore (/usr/local/lib/node_modules/typings/node_modules/configstore/index.js:28:44)
at Object.<anonymous> (/usr/local/lib/node_modules/typings/node_modules/typings-core/dist/utils/store.js:5:19)
at Module._compile (module.js:541:32)
at Object.Module._extensions..js (module.js:550:10)
at Module.load (module.js:458:32)
at tryModuleLoad (module.js:417:12)
```

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--save" "angular2-image-popup"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! angular2-image-popup@1.0.8 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-image-popup@1.0.8 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-image-popup package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-image-popup
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-image-popup
npm ERR! There is likely additional logging output above.

The only way that I found to use this lib is downloading the source from github.

How can I fix this?

**Comment by vimalavinisha** [comment]
Hi, 

```
   Now angular2-image-popup has been working on the angualr rc5.
```

**Comment by Ks89** [comment]
Hi, thank u.
But I'm receiving the same error on "..typings install..".
I cannot install the library. My node_module hasn't "angular2-image-popup" folder

**Comment by Ks89** [comment]
I'm sorry, it was a stupid problem related to this [ISSUE](https://github.com/bower/bower/issues/2262).

Now it's working 👍
